### ISSUE TITLE
/replays/paged game_map parameter is ignored?

### ISSUE THREAD

**Issue by MakiseKurisu** [poma/hotsapi#111] opened 2018-08-07 14:44 UTC
In the sample url http://hotsapi.net/api/v1/replays/paged?page=1&start_date=2018-09-01&game_map=Hanamura you can clear see maps other than Hanamura. I also tried to put the game_map_id in this field which doesn't work either.

Also while we are on it why we are having game from the future?

**Comment by MGatner** [comment] 2018-12-08 01:59
Duplicate of https://github.com/poma/hotsapi/issues/78

**Comment by poma** [comment] 2018-12-08 11:05
I think this query will be deprecated once BigQuery dataset will become available, closing for now

**Closed by poma** 2018-12-08 11:05 UTC
