### ISSUE TITLE
Gateway timeout when searching all replays of a player

### ISSUE THREAD

**Issue by sloonz** [poma/hotsapi#39] opened 2017-09-14 12:51 UTC
```
$ curl -s 'http://hotsapi.net/api/v1/replays?player=Kuban'
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

**Comment by poma** [comment] 2017-09-14 12:52
duplicate of #35

**Closed by poma** 2017-09-14 12:52 UTC
